path:
  ckpt_path: "ZeroShotFastSpeech2/output/ckpt/LibriTTS"
  log_path: "ZeroShotFastSpeech2/output/log/LibriTTS"
  result_path: "ZeroShotFastSpeech2/output/result/LibriTTS"
  configs_path: "ZeroShotFastSpeech2/output/configs/LibriTTS"

optimizer:
  batch_size: 2
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 2000
  log_step: 10
  synth_step: 50
  val_step: 50
  save_step: 50
